{
  "uid" : "5a361ef1d36e4692",
  "name" : "test_div[div_zero2]",
  "fullName" : "test_calc.TestCalc#test_div",
  "historyId" : "73a124f422b5669bb4788ca0e8b70231",
  "time" : {
    "start" : 1612429436987,
    "stop" : 1612429436987,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "Exception: The divisor couldn't be zero!",
  "statusTrace" : "self = <pytest_advanced.testing.test_calc.TestCalc object at 0x000001F88AA166A0>, get_calc = <pytest_advanced.calc.calc.Calculator object at 0x000001F88AA449D0>, div_get_data = [1, 0, 0]\n\n    @allure.story(\"Division Testing\")\n    @pytest.mark.div\n    @allure.severity(allure.severity_level.NORMAL)\n    @pytest.mark.run(order=4)\n    @pytest.mark.flaky(reruns=2, reruns_delay=1)\n    def test_div(self, get_calc, div_get_data):\n        # 调用相除方法\n        with allure.step(\"Computing the division of two numbers\"):\n            divisor = div_get_data[1]\n            if divisor == 0:\n>               raise Exception(\"The divisor couldn't be zero!\")\nE               Exception: The divisor couldn't be zero!\n\ntest_calc.py:40: Exception",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "div_get_data",
    "time" : {
      "start" : 1612429436986,
      "stop" : 1612429436986,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "get_calc",
    "time" : {
      "start" : 1612429436986,
      "stop" : 1612429436986,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "Exception: The divisor couldn't be zero!",
    "statusTrace" : "self = <pytest_advanced.testing.test_calc.TestCalc object at 0x000001F88AA166A0>, get_calc = <pytest_advanced.calc.calc.Calculator object at 0x000001F88AA449D0>, div_get_data = [1, 0, 0]\n\n    @allure.story(\"Division Testing\")\n    @pytest.mark.div\n    @allure.severity(allure.severity_level.NORMAL)\n    @pytest.mark.run(order=4)\n    @pytest.mark.flaky(reruns=2, reruns_delay=1)\n    def test_div(self, get_calc, div_get_data):\n        # 调用相除方法\n        with allure.step(\"Computing the division of two numbers\"):\n            divisor = div_get_data[1]\n            if divisor == 0:\n>               raise Exception(\"The divisor couldn't be zero!\")\nE               Exception: The divisor couldn't be zero!\n\ntest_calc.py:40: Exception",
    "steps" : [ {
      "name" : "Computing the division of two numbers",
      "time" : {
        "start" : 1612429436987,
        "stop" : 1612429436987,
        "duration" : 0
      },
      "status" : "broken",
      "statusMessage" : "Exception: The divisor couldn't be zero!\n",
      "statusTrace" : "  File \"D:\\Study\\Hogwarts\\pytest_advanced\\testing\\test_calc.py\", line 40, in test_div\n    raise Exception(\"The divisor couldn't be zero!\")\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "stepsCount" : 0,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "538f88667728e03c",
      "name" : "stdout",
      "source" : "538f88667728e03c.txt",
      "type" : "text/plain",
      "size" : 122
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "stepsCount" : 1,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "div_get_data::0",
    "time" : {
      "start" : 1612429436989,
      "stop" : 1612429436989,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "story",
    "value" : "Division Testing"
  }, {
    "name" : "feature",
    "value" : "Calculator Testing"
  }, {
    "name" : "tag",
    "value" : "div"
  }, {
    "name" : "tag",
    "value" : "run(order=4)"
  }, {
    "name" : "tag",
    "value" : "flaky(reruns=2, reruns_delay=1)"
  }, {
    "name" : "suite",
    "value" : "test_calc"
  }, {
    "name" : "subSuite",
    "value" : "TestCalc"
  }, {
    "name" : "host",
    "value" : "DESKTOP-D94MS34"
  }, {
    "name" : "thread",
    "value" : "20284-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_calc"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "div_get_data",
    "value" : "[1, 0, 0]"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "81dfe789d2a9b3a1",
      "status" : "broken",
      "statusDetails" : "Exception: The divisor couldn't be zero!",
      "time" : {
        "start" : 1612429435981,
        "stop" : 1612429435981,
        "duration" : 0
      }
    }, {
      "uid" : "93696bf5054ccfe8",
      "status" : "broken",
      "statusDetails" : "Exception: The divisor couldn't be zero!",
      "time" : {
        "start" : 1612429434976,
        "stop" : 1612429434976,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "div", "run(order=4)", "flaky(reruns=2, reruns_delay=1)" ]
  },
  "source" : "5a361ef1d36e4692.json",
  "parameterValues" : [ "[1, 0, 0]" ]
}